### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by dylhole** [charlesweir/BrickPython#4]
I tried `pip install BrickPython` both with and without sudo and got an error I'm having trouble figuring out. Any ideas would be greatly appreciated! 

```
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting BrickPython
Using cached https://files.pythonhosted.org/packages/9a/9c/5833c675f53194085f77ed1cd76b7c6ccaee2e3754f4c8ca7ffd8b6e8edf/BrickPython-0.4.tar.gz
ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-m4lb61i3/BrickPython/setup.py", line 28, in <module>
long_description = read('README.rst')
File "/tmp/pip-install-m4lb61i3/BrickPython/setup.py", line 18, in read
return codecs.open(os.path.join(here, *parts), 'r').read()
File "/usr/lib/python3.4/codecs.py", line 896, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-m4lb61i3/BrickPython/README.rst'
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-m4lb61i3/BrickPython/
```

**Comment by charlesweir** [comment]
Glad to see interest in this. I’m not supporting it these days (don’t have the configuration and hardware to test new versions), but the problem you’re having looks pretty straightforward.

The error says there’s no README.rst file. That is correct. So try creating one by copying README.md (or whatever it is) to README.rst. I don’t suppose it matters what it contains…

Best regards,

Charles

**Comment by dylhole** [comment]
Hey Charles, I appreciate the response even though you're no longer supporting the project! What you've got seems really cool. I've tried programming my BrickPi using multithreading and I've been running into all kinds of Serial errors I haven't been able to figure out. Unfortunately my programming skills are pretty rudimentary too.

I tried what you suggested but it seems like the characters after `tmp/pip-install` in `/tmp/pip-install-m4lb61i3/BrickPython/setup.py` are unique each time you run the installation script so it still produces the same error. I don't want to keep bugging you on this one, but I thought I'd at least share the issue with you. Thanks for your help anyways!

**Comment by charlesweir** [comment]
Try changing the name of the readme file in the distribution?

Best regards,

Charles
